services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./server/data:/app/server/data
      - ./server/apps:/app/server/apps
    stdin_open: true
    tty: true
